#!/bin/sh

${0%/*}/run-tests -d zend_extension=xdebug.so --coverage coverage.html \
  --coverage-src ${0%/*}/../src/functions.php \
  --coverage-src ${0%/*}/../src/TypeValidator.php \
  --coverage-src ${0%/*}/../src/TypeValidator/Exceptions \
  --coverage-src ${0%/*}/../src/TypeValidator/Helpers \
  "$@"
